#!/usr/bin/env python
# coding: utf-8

# In[7]:


import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
mail_content = '''Greetings from DVSR...
************************************************************
Details regarding the event'''
#The mail addresses and password
sender_address = 'kulkarnishreyas.094@gmail.com'
sender_pass = 'vqdilnupcwgpcrpj'
receiver_address = 'rakshithmp04@gmail.com'
#Setup the MIME
message = MIMEMultipart()
message['From'] = 'kulkarnishreyas.094@gmail.com'
message['To'] = 'rakshithmp04@gmail.com'
message['Subject'] = 'A test mail sent by Python. It has an attachment.'   #The subject line
#The body and the attachments for the mail
message.attach(MIMEText(mail_content, 'plain'))
#Create SMTP session for sending the mail
session = smtplib.SMTP('smtp.gmail.com', 587) #use gmail with port
session.starttls() #enable security
session.login(sender_address, sender_pass) #login with mail_id and password
text = message.as_string()
session.sendmail(sender_address, receiver_address, text)
session.quit()
print('Mail Sent')


# In[ ]:


import smtplib


# In[ ]:




